kind: pipeline
type: docker
name: build
steps:
- name: lint
  image: matseee/node:node18.7.0-alpine3.16
  commands:
    - npm install
    - npm run lint
- name: build
  image: matseee/node:node18.7.0-alpine3.16
  commands:
    - npm run build